"""
Cross-paper brainstorming orchestration.

Flow
----
1. Seed round   — each expert proposes research directions from their paper.
2. Cross-pollinate — each expert reads other experts' seeds, retrieves their
   own paper's relevant evidence, and proposes a hybrid idea that combines
   insights from both papers.
3. Synthesize   — the orchestrator's own LLM call writes a structured research
   agenda, giving priority to the cross-paper combinations.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from itertools import count

from .blackboard import Evidence
from .llm import OpenRouterLLM, PaperExpertLLM


# ── Data model ────────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class ResearchIdea:
    """A research direction proposed by one expert from their paper."""

    idea_id: str
    agent_id: str
    paper_id: str
    paper_title: str
    text: str        # one-sentence description of the direction
    grounding: str   # which method/finding from the paper enables this
    gap: str         # the specific open question or opportunity
    evidence: list[Evidence]


@dataclass(frozen=True)
class CrossPollinatedIdea:
    """
    A new research direction generated by one expert after reading another
    expert's seed — combining insights from both papers.
    """

    cp_id: str
    from_agent_id: str   # the expert who generated this idea
    from_paper_id: str
    from_paper_title: str
    seed_idea_id: str    # the seed that was read
    seed_paper_id: str
    seed_paper_title: str
    text: str            # the hybrid research direction
    connection: str      # how the two papers specifically intersect here
    evidence: list[Evidence]


@dataclass
class BrainstormBlackboard:
    """Auditable state for a cross-paper brainstorm session."""

    area: str
    seeds: list[ResearchIdea] = field(default_factory=list)
    cross_pollinations: list[CrossPollinatedIdea] = field(default_factory=list)
    agenda: str | None = None
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def add_seed(self, idea: ResearchIdea) -> None:
        self.seeds.append(idea)

    def add_cross_pollination(self, idea: CrossPollinatedIdea) -> None:
        self.cross_pollinations.append(idea)


# ── Parsing helpers ───────────────────────────────────────────────────────────

def _parse_ideas(text: str, agent_id: str, paper_id: str, paper_title: str,
                 evidence: list[Evidence], id_counter: count) -> list[ResearchIdea]:
    """
    Extract structured ResearchIdea objects from the LLM's response.
    Falls back to treating the whole response as one idea if parsing fails.
    """
    ideas: list[ResearchIdea] = []
    blocks = re.split(r"---IDEA---", text, flags=re.IGNORECASE)
    for block in blocks:
        block = block.strip()
        if not block or "---END---" not in block.upper():
            continue
        block = re.split(r"---END---", block, flags=re.IGNORECASE)[0].strip()

        text_val   = _field(block, "TEXT")
        grounding  = _field(block, "GROUNDING")
        gap        = _field(block, "GAP")

        if not text_val:
            continue

        ideas.append(ResearchIdea(
            idea_id=f"{paper_id}:idea:{next(id_counter)}",
            agent_id=agent_id,
            paper_id=paper_id,
            paper_title=paper_title,
            text=text_val,
            grounding=grounding or "(see paper)",
            gap=gap or "(not specified)",
            evidence=evidence,
        ))

    if not ideas:
        # graceful fallback — treat whole response as one idea
        first_sentence = text.split(".")[0].strip() + "."
        ideas.append(ResearchIdea(
            idea_id=f"{paper_id}:idea:{next(id_counter)}",
            agent_id=agent_id,
            paper_id=paper_id,
            paper_title=paper_title,
            text=first_sentence,
            grounding="(see full response)",
            gap="(see full response)",
            evidence=evidence,
        ))
    return ideas


def _parse_cross_pollination(
    text: str,
    from_agent_id: str,
    from_paper_id: str,
    from_paper_title: str,
    seed: ResearchIdea,
    evidence: list[Evidence],
    id_counter: count,
) -> CrossPollinatedIdea:
    """Extract one CrossPollinatedIdea from the LLM's response."""
    cp_text   = ""
    cp_conn   = ""

    block = text
    if "---CROSSPOLLINATE---" in text.upper():
        parts = re.split(r"---CROSSPOLLINATE---", text, flags=re.IGNORECASE)
        if len(parts) > 1:
            block = re.split(r"---END---", parts[1], flags=re.IGNORECASE)[0].strip()

    cp_text = _field(block, "TEXT") or block.split(".")[0].strip() + "."
    cp_conn = _field(block, "CONNECTION") or "(see full response)"

    return CrossPollinatedIdea(
        cp_id=f"{from_paper_id}:cp:{next(id_counter)}",
        from_agent_id=from_agent_id,
        from_paper_id=from_paper_id,
        from_paper_title=from_paper_title,
        seed_idea_id=seed.idea_id,
        seed_paper_id=seed.paper_id,
        seed_paper_title=seed.paper_title,
        text=cp_text,
        connection=cp_conn,
        evidence=evidence,
    )


def _field(text: str, name: str) -> str:
    """Extract 'NAME: value' from a block of text (case-insensitive)."""
    pattern = re.compile(rf"^{re.escape(name)}:\s*(.+)", re.IGNORECASE | re.MULTILINE)
    match = pattern.search(text)
    return match.group(1).strip() if match else ""


# ── Orchestrator ──────────────────────────────────────────────────────────────

class BrainstormOrchestrator:
    """
    Orchestrates a cross-paper brainstorming session.

    Agents first seed ideas from their own papers, then cross-pollinate
    by combining their paper's insights with other agents' seeds.
    The orchestrator synthesizes the results into a research agenda.
    """

    def __init__(
        self,
        agents: list,              # list[PaperExpertAgent]
        *,
        llm: PaperExpertLLM | None = None,
        max_agents: int = 6,
        cross_pollinate_rounds: int = 1,
        logger=None,
    ) -> None:
        if not agents:
            raise ValueError("BrainstormOrchestrator requires at least one agent.")
        self.agents = agents
        self.llm = llm or OpenRouterLLM()
        self.max_agents = max_agents
        self.cross_pollinate_rounds = cross_pollinate_rounds
        self.logger = logger
        self._idea_counter: count = count(1)
        self._cp_counter: count = count(1)

    def run(self, area: str) -> BrainstormBlackboard:
        log = self.logger
        bb = BrainstormBlackboard(area=area)

        # Select agents most relevant to this research area
        if log:
            log.phase("Selecting relevant experts")
        selected = self._select_agents(area)
        if log:
            log.selected([a.agent_id for a in selected])
            log.info(f"{len(selected)} expert(s) will participate")

        # ── Seed round ────────────────────────────────────────────────────
        if log:
            log.phase(f"Seed round — each expert proposes research directions ({len(selected)} agents)")
        for agent in selected:
            ideas = agent.propose_research(area, self._idea_counter)
            for idea in ideas:
                bb.add_seed(idea)
        if log:
            log.phase_done(f"{len(bb.seeds)} seed idea(s) generated")

        # ── Cross-pollination ─────────────────────────────────────────────
        if len(selected) > 1:
            total = self.cross_pollinate_rounds * len(selected) * max(0, len(selected) - 1)
            if log:
                log.phase(
                    f"Cross-pollination — agents combine insights across papers "
                    f"({self.cross_pollinate_rounds} round(s), up to {total} hybrid idea(s))"
                )
            for rnd in range(self.cross_pollinate_rounds):
                if log and self.cross_pollinate_rounds > 1:
                    log.info(f"Round {rnd + 1}/{self.cross_pollinate_rounds}")
                for agent in selected:
                    # Each agent reads every other agent's seeds
                    other_seeds = [s for s in bb.seeds if s.agent_id != agent.agent_id]
                    for seed in other_seeds:
                        cp = agent.cross_pollinate(area, seed, self._cp_counter)
                        bb.add_cross_pollination(cp)
            if log:
                log.phase_done(f"{len(bb.cross_pollinations)} hybrid idea(s) generated")
        else:
            if log:
                log.info("Only one expert — skipping cross-pollination (need 2+ papers)")

        # ── Synthesis ─────────────────────────────────────────────────────
        if log:
            log.phase("Synthesizing research agenda")
        bb.agenda = self._synthesize(bb)
        if log:
            log.phase_done("Research agenda ready")

        return bb

    # ── internal ──────────────────────────────────────────────────────────────

    def _select_agents(self, area: str) -> list:
        ranked = sorted(
            self.agents,
            key=lambda a: a.relevance(area),
            reverse=True,
        )
        return ranked[: self.max_agents]

    def _synthesize(self, bb: BrainstormBlackboard) -> str:
        log = self.logger

        seeds_text = "\n\n".join(
            f"[{s.paper_title}]\n"
            f"  Direction: {s.text}\n"
            f"  Grounded in: {s.grounding}\n"
            f"  Gap addressed: {s.gap}"
            for s in bb.seeds
        )

        cp_text = "\n\n".join(
            f"[{cp.from_paper_title}] × [{cp.seed_paper_title}]\n"
            f"  Hybrid direction: {cp.text}\n"
            f"  How they connect: {cp.connection}"
            for cp in bb.cross_pollinations
        ) or "  (none — only one paper in session)"

        paper_list = ", ".join(
            sorted({s.paper_title for s in bb.seeds})
        )

        messages = [
            {
                "role": "system",
                "content": (
                    "You are a research strategist synthesizing a multi-paper expert panel "
                    "into a concrete, actionable research agenda. "
                    "Prioritize directions that combine insights from multiple papers — "
                    "these represent the most novel opportunities."
                ),
            },
            {
                "role": "user",
                "content": "\n\n".join([
                    f"Research area: {bb.area}",
                    f"Papers in session: {paper_list}",
                    "═" * 60,
                    "SEED IDEAS (from each paper independently):",
                    seeds_text,
                    "═" * 60,
                    "CROSS-PAPER HYBRID IDEAS (combining multiple papers):",
                    cp_text,
                    "═" * 60,
                    "Task: Synthesize the above into a research agenda with 3-5 high-impact "
                    "directions. For each direction:\n"
                    "- Prefer ideas that combine insights from multiple papers\n"
                    "- Be specific: name which methods/findings intersect\n"
                    "- Include a concrete first step a researcher could take next week\n\n"
                    "Format your response as:\n"
                    "## Research Agenda: {area}\n\n"
                    "### [Direction Title]\n"
                    "**Core idea**: ...\n"
                    "**Papers it draws from**: ...\n"
                    "**Why this is promising**: ...\n"
                    "**First step**: ...\n\n"
                    "[repeat]\n\n"
                    "### Open Questions\n"
                    "- ...",
                ]),
            },
        ]

        can_stream = hasattr(self.llm, "complete_stream")
        if log:
            log.agent_start("orchestrator", "synthesizing")

        if log and can_stream:
            result = self.llm.complete_stream(messages, log.on_token)  # type: ignore[attr-defined]
        else:
            result = self.llm.complete(messages)

        if log:
            log.agent_done("orchestrator")

        return result
